import { JobAccount } from "./jobaccount";


export class JobMaster {
    JobID: number;
    CompJobID: number;
    Status: number;
    JobTitle: string;
    JobTypeID: number;
    JobTypeName: string;
    JobCategory: string;
    JobDescription: string;
    DurationInYears?: number;
    DurationInMonths?: number;
    BillingRate?: number;
    BillingType?: number;
    MinExperience?: number;
    MaxExperience?: number;
    Experience: string;
    MinSalary: string;
    MaxSalary: string;
    SkillSet: string;
    Email: string;
    PrimaryPhoneNumber: string;
    SecondaryPhoneNumber: string;
    Location: string;
    CreatedBy: string;
    CreatedDate: Date;
    UpdatedDate: Date;
    Accounts: string;
    CompanyName: string;
    Education: string;
    JobCreatedBy: string;
    Hashtags: string;
    WorkStatus: string;
    IsBenchJob: boolean;
    labels: string[];
    Rate: string;
    Duration: string;
    StatusName: string;
    CompanyJobId: string;
    JobCategoryName: string;
    BillingTypeName: string;
    TravelRequirement?: number;
    AccountMasters: JobAccount[];
    City: string;
    State: string;
    ZipCode: number;
    JobLocationType :string;
    CompanyId:number;
    MappedApplicants:number;
    NotesCount:number;
    WorkFromHome:boolean;
    SalaryType:number;
    JobPostingDate:Date;
    UniqueJobId:string;
    JobSource:string;
    POC:string;
    MappedRequisitions:number;
    PublishedJobUrl:string;
    Logo:string;
    VisaSponsorship:string;
    ContractType:string;
    salaryRangeType:number;
    constructor() {
        this.JobID = 0;
        this.CompJobID = 0;
        this.Status = 0;
        this.JobTitle = null;
        this.JobTypeID = 0;
        this.JobTypeName = null;
        this.JobCategory = null;
        this.JobDescription = null;
        this.DurationInYears = null;
        this.DurationInMonths = null;
        this.BillingRate = null;
        this.BillingType = null;
        this.MinExperience = null;
        this.MaxExperience = null;
        this.MinSalary = null;
        this.MaxSalary = null;
        this.SkillSet = null;
        this.Email = null;
        this.PrimaryPhoneNumber = null;
        this.SecondaryPhoneNumber = null;
        this.Location = null;
        this.CreatedBy = null;
        this.CreatedDate = new Date();
        this.UpdatedDate = new Date();
        this.Accounts = null;
        this.CompanyName = null;
        this.Education = null;
        this.JobCreatedBy = null;
        this.Hashtags = null;
        this.WorkStatus = null;
        this.IsBenchJob = false;
        this.labels = [];
        this.Experience = null;
        this.Rate = null;
        this.Duration = null;
        this.StatusName = null;
        this.CompanyJobId = null;
        this.JobCategoryName = null;
        this.BillingTypeName = null;
        this.TravelRequirement = null;
        this.AccountMasters = [];
        this.City=null;
        this.State=null;
        this.ZipCode=null;
        this.JobLocationType=null;
        this.CompanyId=0;
        this.MappedApplicants=0;
        this.NotesCount=0;
        this.WorkFromHome=false;
        this.SalaryType=0;
        this.JobPostingDate=null;
        this.UniqueJobId=null;
        this.JobSource=null;
        this.POC=null;
        this.MappedRequisitions=0;
        this.PublishedJobUrl=null;
        this.Logo=null;
        this.VisaSponsorship=null;
        this.ContractType=null;
        this.salaryRangeType=0;
    }
}