// icon.service.ts
import { Injectable } from '@angular/core';
import icDownload from '@iconify/icons-ic/twotone-cloud-download';
import icSearch from '@iconify/icons-ic/twotone-search';
import icEye from '@iconify/icons-ic/twotone-remove-red-eye';
import icFilterList from '@iconify/icons-ic/twotone-filter-list';
import icEdit from '@iconify/icons-ic/twotone-edit';
import icAdd from '@iconify/icons-ic/twotone-add';
import icDelete from '@iconify/icons-ic/twotone-delete';
import icPerson from '@iconify/icons-ic/twotone-person';
import icRemove_Circle_Outline from '@iconify/icons-ic/remove-circle-outline';
import icArrowDropDown from '@iconify/icons-ic/twotone-arrow-drop-down';
import icPersonAdd from '@iconify/icons-ic/twotone-person-add';
import icShare from '@iconify/icons-ic/twotone-share';
import icRestore from '@iconify/icons-ic/twotone-restore';
import icratereview from '@iconify/icons-ic/twotone-rate-review';
import icComment from '@iconify/icons-ic/twotone-comment';
import iclocationon from '@iconify/icons-ic/location-on';
import icVisibility from '@iconify/icons-ic/twotone-visibility';
import icVisibilityOff from '@iconify/icons-ic/twotone-visibility-off';
import icPhone from '@iconify/icons-ic/twotone-phone';
import icMail from '@iconify/icons-ic/twotone-mail';
import icInsert_Drive_File from '@iconify/icons-ic/insert-drive-file';
import icsettings_backup_restore from '@iconify/icons-ic/twotone-settings-backup-restore';
import icCloudDownload from '@iconify/icons-ic/twotone-cloud-download';
import icBack from '@iconify/icons-ic/twotone-arrow-back';
import icPrint from '@iconify/icons-ic/twotone-print';
import icInfo from '@iconify/icons-ic/twotone-info';
import icDoneAll from '@iconify/icons-ic/twotone-done-all';
import icschedule from '@iconify/icons-ic/schedule';
import icaccount from '@iconify/icons-ic/supervisor-account';
import icnote from '@iconify/icons-ic/note';
import icCancel from '@iconify/icons-ic/twotone-cancel';
import icClearAll from '@iconify/icons-ic/twotone-clear-all';
import icClose from '@iconify/icons-ic/twotone-close';
import icfileupload from '@iconify/icons-ic/file-upload';
import icPictureAsPdf from '@iconify/icons-ic/twotone-picture-as-pdf';
import icdelete from '@iconify/icons-ic/delete';
import icvieweye from '@iconify/icons-ic/remove-red-eye';
import icInsertComment from '@iconify/icons-ic/twotone-insert-comment';
import icMoreVert from '@iconify/icons-ic/twotone-more-vert';
import icMyLocation from '@iconify/icons-ic/twotone-my-location';
import icLocationCity from '@iconify/icons-ic/twotone-location-city';
import icEditLocation from '@iconify/icons-ic/twotone-edit-location';
import icMoreHoriz from '@iconify/icons-ic/twotone-more-horiz';
import icFolder from '@iconify/icons-ic/twotone-folder';
import icMap from '@iconify/icons-ic/twotone-map';
import IcRefresh from '@iconify/icons-ic/refresh';
import icHistory from '@iconify/icons-ic/twotone-history';
import icArchived from '@iconify/icons-ic/twotone-archive';
import icWarning from '@iconify/icons-ic/twotone-warning';
import icBook from '@iconify/icons-ic/twotone-book';
import icPublish from '@iconify/icons-ic/twotone-publish';
import icAssigment from '@iconify/icons-ic/twotone-assignment';
import icFormattedList from '@iconify/icons-ic/twotone-format-list-bulleted';
import icLayers from '@iconify/icons-ic/twotone-layers';
import icReports from '@iconify/icons-ic/twotone-report';
import icDescription  from '@iconify/icons-ic/twotone-description';
import icdashboard from '@iconify/icons-ic/twotone-dashboard';
import icSettings from '@iconify/icons-ic/settings';
import icHome  from '@iconify/icons-ic/home';
import icBusiness  from '@iconify/icons-ic/business';
import icPerm_Data_Setting  from '@iconify/icons-ic/perm-data-setting';
import icPayment  from '@iconify/icons-ic/payment';
import icSettings_Applications  from '@iconify/icons-ic/settings-applications';
import icAnnouncement  from '@iconify/icons-ic/announcement';
import icView_Module from '@iconify/icons-ic/view-module';
import icVerifiedUser  from '@iconify/icons-ic/verified-user';
import isSupervised_User_Circle  from '@iconify/icons-ic/sharp-supervised-user-circle';

@Injectable({
  providedIn: 'root'
})
export class IconService {
  icDownload = icDownload;
  icSearch=icSearch;
  icEye = icEye;
  icFilterList = icFilterList;
  icAdd = icAdd;
  icDelete = icDelete;
  icPerson = icPerson;
  icPersonAdd = icPersonAdd;
  icArrowDropDown = icArrowDropDown;
  icRemove_Circle_Outline = icRemove_Circle_Outline;
  icShare = icShare;
  icRestore = icRestore;
  icratereview = icratereview;
  icComment = icComment;
  iclocationon = iclocationon;
  icVisibility = icVisibility;
  icVisibilityOff = icVisibilityOff;
  icPhone = icPhone;
  icMail = icMail;
  icInsert_Drive_File = icInsert_Drive_File;
  icsettings_backup_restore = icsettings_backup_restore;
  icEdit = icEdit;
  icCloudDownload = icCloudDownload;
  icBack = icBack;
  icPrint = icPrint;
  icInfo = icInfo;
  icDoneAll = icDoneAll;
  icschedule = icschedule;
  icAccount = icaccount;
  icnote = icnote;
  icCancel=icCancel;
  icClearAll=icClearAll;
  icClose=icClose;
  icfileupload=icfileupload;
  icPictureAsPdf=icPictureAsPdf;
  icdelete=icdelete;
  icvieweye=icvieweye;
  icInsertComment=icInsertComment;
  icMyLocation = icMyLocation;
  icLocationCity = icLocationCity;
  icEditLocation = icEditLocation;
  icMoreVert = icMoreVert;
  icMap = icMap;
  icMoreHoriz = icMoreHoriz;
  icFolder = icFolder;
  IcRefresh = IcRefresh;
  icHistory=icHistory;
  icArchived = icArchived;
  icWarning=icWarning;
  icBook=icBook;
  icPublish=icPublish;
  icAssigment=icAssigment;
  icFormattedList=icFormattedList;
  icLayers=icLayers;
  icReports=icReports;
  icDescription=icDescription;
  icdashboard=icdashboard;
  icSettings=icSettings;
  icHome=icHome;
  icBusiness=icBusiness;
  icPerm_Data_Setting=icPerm_Data_Setting;
  icPayment=icPayment;
  icSettings_Applications=icSettings_Applications;
  icAnnouncement=icAnnouncement;
  icView_Module=icView_Module;
  icVerifiedUser=icVerifiedUser;
  isSupervised_User_Circle=isSupervised_User_Circle;
}
