export class Job {
    JobID: number;
    CompJobID: number;
    Status: number;
    JobTitle: string;
    JobTypeID: number;
    JobCategory: string;
    WorkStatus: string;
    Address1: string;
    Address2: string;
    City: string;
    State: string;
    Country: string;
    ZipCode: string;
    Email: string;
    CompanyName: string;
    Education: string;
    PrimaryPhoneNumber: string;
    CreatedBy: string;
    CreatedDate: Date;
    UpdatedDate?: Date;
    UpdatedBy: string;
    CompanyID: number;
    JobDescription: string;
    CompanyJobId: string;
    DurationInYears:number;
    DurationInMonths:Number;
    Location:string;
    labels:string[];
    constructor() {
        this.JobID=0;
        this.CompJobID=0;
        this.Status=0;
        this.JobTitle=null;
        this.JobTypeID=0;
        this.JobCategory=null;
        this.WorkStatus=null;
        this.Address1=null;
        this.Address2=null;
        this.City=null;
        this.State=null;
        this.Country=null;
        this.ZipCode=null;
        this.Email=null;
        this.CompanyName=null;
        this.Education=null;
        this.PrimaryPhoneNumber=null;
        this.CreatedBy=null;
        this.CreatedDate=new Date();
        this.UpdatedDate=null;
        this.UpdatedBy=null;
        this.CompanyID=0;
        this.JobDescription=null;
        this.CompanyJobId=null;
        this.DurationInYears=0;
        this.DurationInMonths=0;
        this.Location=null;
        this.labels=[];
    }
}