export class SubmissionsList {
    SubmissionId: number;
    CompSubmissionId: number;
    JobId: number;
    JobTitle: string;
    JobState: string;
    JobCity: string;
    SubmittedBy: string;
    SubmittedByName: string;
    SubmittedDate: Date;
    SubmissionStatus: number;
    SubmissionStatusName: string;
    CandidateId: number;
    Client: string;
    candidateName: string;
    canidateEmail: string;
    JobRate: string;
    SubmissionRate?: number;
    SubmissionRateType: string;
    JobBillingType: string;
    SubmissionType: number;
    SubmissionTypeName: string;
    IsShowContactInfo: boolean;
    CandidateRate: string;
    CandidateBillingType: string;
    EmploymentTerm: string;
    CandidateCreatedBy: string;
    CompanySubmissionID: string;
    SchedulesCount: number;
    Location:string;
    ShortName:string;
    constructor(){
    this.SubmissionId=0;
    this.CompSubmissionId=0;
    this.JobId=0;
    this.JobTitle=null;
    this.JobState=null;
    this.JobCity=null;
    this.SubmittedBy=null;
    this.SubmittedByName=null;
    this.SubmittedDate=new Date();
    this.SubmissionStatus=0;
    this.SubmissionStatusName=null;
    this.CandidateId=0;
    this.Client=null;
    this.candidateName=null;
    this.canidateEmail=null;
    this.JobRate=null;
    this.SubmissionRate=null;
    this.SubmissionRateType=null;
    this.JobBillingType=null;
    this.SubmissionType=0;
    this.SubmissionTypeName=null;
    this.IsShowContactInfo=false;
    this.CandidateRate=null;
    this.CandidateBillingType=null;
    this.EmploymentTerm=null;
    this.CandidateCreatedBy=null;
    this.CompanySubmissionID=null;
    this.SchedulesCount=0;
    this.Location=null;
    this.ShortName=null;
    }
}