export class OnBoardingCompanies{
    CompanyID:number;    
    CompanyName:string;
    Website :string;
    PrimaryEmail:string;
    Logo:string;
    Description:string;
    IsActive:boolean;
    CreatedDate: Date;
    City: string;
    State: string;
    SuperAdminId:string;
    IsEmailConfirmed:boolean;
    RemainingDays:number;
    FirstName:string;
    LastName:string;
    PhoneNo:string;
    IsPaidcompany:boolean;
    IsVisible:boolean;
    EmpCandidateCount:number;
    onboarding_status:string;
    ZipCode:String;
    Display_DateFormat:string;
    Display_TimeFormat:string;
    TimeZoneName:string;
    bgClass:string;
    Address1:string;
    Address2:string;
    EmailConfirmed:boolean;
    constructor(){
        this.CompanyID=0;
        this.CompanyName=null;
        this.Website=null;
        this.PrimaryEmail=null;
        this.Logo=null;
        this.Description=null;
        this.IsActive=false;
        this.CreatedDate=null;
        this.City=null;
        this.State=null;
        this.SuperAdminId=null;
        this.IsEmailConfirmed=false;
        this.RemainingDays=0;
        this.FirstName=null;
        this.LastName=null;
        this.PhoneNo=null;
        this.IsPaidcompany=false;
        this.IsVisible=false;
        this.EmpCandidateCount=0;
        this.onboarding_status=null;
        this.ZipCode=null;
        this.Display_DateFormat=null;    
        this.Display_TimeFormat=null;
        this.TimeZoneName=null;
        this.bgClass=null;
        this.Address1=null;
        this.Address2=null;
        this.EmailConfirmed = false;
    }
}