import { ActivityLogSubmission } from "./submissionactivitylog";
export class InterviewList {
    JobId: number;
    JobTitle: string;
    JobState: string;
    JobCity: string;
    SubmissionId: number;
    SubmittedBy: string;
    SubmittedByName: string;
    SubmittedDate: Date;
    SubmissionStatus: number;
    SubmissionStatusName: string;
    SubmittedRate: string;
    InterviewStatus: number;
    InterviewStatusName: string;
    InterviewTitle: string;
    InterviewType: string;
    InterviewDate: Date;
    InterviewTimeZone: string;
    InterviewDuration: string;
    ScheduleId: number;
    CandidateId:number;
    CandidateName: string;
    CanidateEmail: string;
    CandidateCreatedBy: string;
    BenchsubmissionId: number;
    BenchCandidateId:number;
    Client: string;
    LastUpdatedName: string;
    LastUpdatedDate: Date;
    IsUpdated: number;
    ScheduleComments: string;
    Location:string;
    UpdatedBy:string;
    CreatedBy:string;
    ActivityLogs:ActivityLogSubmission[];
    Statuslabels:string;
    textClass:string;
    bgClass:string;
    NotesCount:number;
    ShortName:string;
    InterviewRound:string;
    InterviewRoundName:string;
    InterviewTypeName:string;
    constructor() {
        this.JobId = 0;
        this.JobTitle = null;
        this.JobState = null;
        this.JobCity = null;
        this.SubmissionId = 0;
        this.SubmittedBy = null;
        this.SubmittedByName = null;
        this.SubmittedDate = new Date();
        this.SubmissionStatus = 0;
        this.SubmissionStatusName = null;
        this.SubmittedRate = null;
        this.InterviewStatus = 0;
        this.InterviewStatusName = null;
        this.InterviewTitle = null;
        this.InterviewType = null;
        this.InterviewDate = new Date();
        this.InterviewTimeZone = null;
        this.InterviewDuration = null;
        this.ScheduleId = 0;
        this.CandidateId=0;
        this.CandidateName = null;
        this.CanidateEmail = null;
        this.CandidateCreatedBy = null;
        this.BenchsubmissionId = 0;
        this.Client = null;
        this.LastUpdatedName = null;
        this.LastUpdatedDate = new Date();
        this.IsUpdated = 0;
        this.ScheduleComments = null;
        this.Location=null;
        this.UpdatedBy=null;
        this.BenchCandidateId=0;
        this.CreatedBy=null;
        this.ActivityLogs=[];
        this.textClass=null;
        this.bgClass=null;
        this.NotesCount=0;
        this.ShortName=null;
        this.InterviewRound=null;
        this.InterviewRoundName=null;
        this.InterviewTypeName=null;
    }

}

