import { AssignmentMaster } from './assignmentmaster';
import { EmployeeDocuments } from './employeedocuments';
export class EmployeeMaster {
    EmployeeID: number;
    CompEmployeeID: number;
    ComapnyEmployeeID:string;
    Status: number;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    Email: string;
    PrimaryPhoneNumber: string;
    SecondaryPhoneNumber: string;
    Address1: string;
    Address2: string;
    City: string;
    State: string;
    Country: string;
    ZipCode: string
    EmployeeType: string;
    EmploymentType: string;
    Classification: string;
    Department: string;
    Designation: string;
    WorkStatus: string;
    WorkStatusExpiry: Date;
    EmpStartDate: Date;
    EmpEndDate: Date;
    HealthInsuranceEnrolled: boolean;
    CandidateID: number;
    Notes: string;
    HRManager: string;
    FinanceManager: string;
    TrainingManager: string;
    ATSManager:string;
    ATSRole:string;
    EMPCentralRole:string;
    CRMRole:string;
    DocVaultRole:string;
    WebsiteUser: string;
    CompanyID: number;
    CreatedBy: string;
    CreatedDate: Date
    UpdatedBy: string;
    UpdatedDate: Date;
    DOB: string;
    Gender: string;
    MaritalStatus: string;
    CreateUserAccount: boolean;
    PlacementID:number;
    HRManager_Name:string;
    AssignmentMasters: AssignmentMaster[];
    EmployeeDocuments:EmployeeDocuments[];
    RemoteAssignment:boolean;
    AmendmentRequired:boolean;
    AssignmentStatus:number;
    LastWorkingDate:string;
    TerminationDate :string;
    TerminationReason :string;
    LaptopReturned :boolean;
    EligibleForRehire :boolean;
    WorkStatusEffective:Date;
    WSExpiryPriority:number;
    StatusName:string;
    FinanceManager_Name:string;
    TrainingManager_Name:string;
    FailType:string;
    I94Number:string;
    I94ExpiryDate:Date;
    IsCVAccess:boolean;
    ImmigrationManager:string;
    ImmigrationManager_Name:string;
    constructor() {
        this.EmployeeID = 0;
        this.CompEmployeeID = 0;
        this.ComapnyEmployeeID=null;
        this.Status = 0;
        this.FirstName = null;
        this.MiddleName = null;
        this.LastName = null;
        this.Email = null;
        this.PrimaryPhoneNumber = null;
        this.SecondaryPhoneNumber = null;
        this.Address1 = null;
        this.Address2 = null;
        this.City = null;
        this.State = null;
        this.Country = null;
        this.ZipCode = null;
        this.EmployeeType = null;
        this.EmploymentType = null;
        this.Classification = null;
        this.Department = null;
        this.Designation = null;
        this.WorkStatus = null;
        this.WorkStatusExpiry = new Date();
        this.EmpStartDate = null;
        this.EmpEndDate = null;
        this.HealthInsuranceEnrolled = false;
        this.CandidateID = 0;
        this.Notes = null;
        this.HRManager = null;
        this.FinanceManager = null;
        this.TrainingManager = null;
        this.ATSManager=null;
        this.ATSRole=null;
        this.EMPCentralRole=null;
        this.CRMRole=null;
        this.DocVaultRole=null;
        this.WebsiteUser = null;
        this.CompanyID = 0;
        this.CreatedBy = null;
        this.CreatedDate = new Date();
        this.UpdatedBy = null;
        this.UpdatedDate = new Date();
        this.DOB = null;
        this.Gender = null;
        this.MaritalStatus = null;
        this.CreateUserAccount= false;
        this.AssignmentMasters= [];
        this.PlacementID=0;
        this.EmployeeDocuments=[];
        this.HRManager_Name=null;
        this.RemoteAssignment=false;
        this.AmendmentRequired=false;
        this.AssignmentStatus=0;
        this.WorkStatusEffective=null;
        this.WSExpiryPriority=0;
        this.StatusName=null;
        this.FinanceManager_Name=null;
        this.TrainingManager_Name=null;
        this.FailType=null;
        this.I94Number=null;
        this.I94ExpiryDate=null;
        this.IsCVAccess=false;
        this.ImmigrationManager = null;
        this.ImmigrationManager_Name = null;
    }
}