import { EmployeeMaster } from './employeemaster';
import { AssignmentMaster } from './assignmentmaster';
import { PlacementAccountMappings } from './placement';
import { PlacementDocuments } from './placementdocuments';
export class PlacementOnBoarding {

    PlacementID: number;
    CompPlacementID: number;
    ComapnyPlacementID: string;
    Status: number;
    CandidateID: number;
    JobID: number;
    PlacementType: string;
    StartDate: Date;
    EndDate?: Date;
    BillRate: string;
    BillRateType?: number;
    JobCategory: number;
    PlacementPOC: string;
    CompanyID: number;
    EmployeeID: string;
    CreatedBy: string;
    CreatedDate: Date;
    UpdatedBy: string;
    UpdatedDate?: Date;
    PlacementPrefix: string;
    IsDeleted: boolean;
    CandFirstName: string;
    CandMiddleName: string;
    CandLastName: string;
    CandEmail: string;
    CandPhoneNumber: string;
    CandWorkStatus: string;
    CandWorkStatusExpiry?: Date;
    CandExperienceYears: string;
    CompCandidateId: number;
    CandAddress1: string;
    CandAddress2: string;
    CandCity: string;
    CandState: string;
    CandCountry: string;
    CandZipCode: string;
    CompJobId: number;
    JobTitle: string;
    JobTypeID: number;
    JobWorkStatus: string;
    JobEducation: string;
    JobDescription: string;
    InvoiceCycle?: number;
    PaymentTerms?: number;
    InvoicingEmail: string;
    EndClient: string;
    WLAddress1: string;
    WLAddress2: string;
    WLCity: string;
    WLState: string;
    WLCountry: string;
    WLZipCode: string;
    Notes: string;
    BillRateEffectiveDate?: Date;
    Employee: EmployeeMaster;
    Assignment: AssignmentMaster;
    PlacementAccountMappings: PlacementAccountMappings[];
    PlacementDocuments: PlacementDocuments[];
    StatusName:string;
    PlacementPOCName:string;
    constructor() {
        this.PlacementID = 0;
        this.CompPlacementID = 0;
        this.ComapnyPlacementID = null;
        this.Status = 0;
        this.CandidateID = 0;
        this.JobID = 0;
        this.PlacementType = null;
        this.StartDate = new Date();
        this.EndDate = null;
        this.BillRate = null;
        this.BillRateType = null;
        this.JobCategory = null;
        this.PlacementPOC = null;
        this.CompanyID = 0;
        this.EmployeeID = null;
        this.CreatedBy = null;
        this.CreatedDate = new Date();
        this.UpdatedBy = null;
        this.UpdatedDate = null;;
        this.PlacementPrefix = null;
        this.IsDeleted = false;
        this.CandFirstName = null;
        this.CandMiddleName = null;
        this.CandLastName = null;
        this.CandEmail = null;
        this.CandPhoneNumber = null;
        this.CandWorkStatus = null;
        this.CandWorkStatusExpiry = null;
        this.CandExperienceYears = null;
        this.CompCandidateId = 0;
        this.CandAddress1 = null;
        this.CandAddress2 = null;
        this.CandCity = null;
        this.CandState = null;
        this.CandCountry = null;
        this.CandZipCode = null;
        this.CompJobId = 0;
        this.JobTitle = null;
        this.JobTypeID = 0;
        this.JobWorkStatus = null;
        this.JobEducation = null;
        this.JobDescription = null;
        this.InvoiceCycle = null;
        this.PaymentTerms = null;
        this.InvoicingEmail = null;
        this.EndClient = null;
        this.WLAddress1 = null;
        this.WLAddress2 = null;
        this.WLCity = null;
        this.WLState = null;
        this.WLCountry = null;
        this.WLZipCode = null;
        this.Notes = null;
        this.BillRateEffectiveDate = null;
        this.Employee = new EmployeeMaster();
        this.Assignment = new AssignmentMaster();
        this.PlacementAccountMappings = [];
        this.PlacementDocuments = [];
        this.StatusName=null;
        this.PlacementPOCName=null;
    }
}