export class AssignmentMaster {
    AssignmentID: number;
    CompAssignmentID: number;
    AssignmentName: string;
    Status: number;
    AssignmentType: string;
    AsmtCategory?: number;
    AsmtCategoryName:string;
    StartDate: Date;
    EndDate?: Date;
    BillingRate: string;
    BillRateType?: number;
    AsmtClassification: string;
    WLAddress1: string;
    WLAddress2: string;
    WLCity: string;
    WLState: string;
    WLCountry: string;
    WLZipCode: string;
    PlacementPOC: string;
    EmployeeID: number;
    IsDeleted: boolean;
    TimeSheet: boolean;
    CompanyID: number;
    CreatedBy: string;
    CreatedDate: Date;
    UpdatedBy: string;
    UpdatedDate?: Date;
    CompanyAssignmentId: string;
    PlacementID: number;
    RemoteAssignment: boolean;
    AmendmentRequired: boolean;
    assignDisable: boolean;
    ComapnyEmployeeID:string;
    EmployeeFirstName:string;
    EmployeeLastName:string;
    constructor() {
        this.AssignmentID = 0;
        this.CompAssignmentID = 0;
        this.AssignmentName = null;
        this.Status = 1;
        this.AssignmentType = null;
        this.AsmtCategory = null;
        this.AsmtCategoryName=null;
        this.StartDate = new Date();
        this.EndDate = null;
        this.BillingRate = null;
        this.BillRateType = null;
        this.AsmtClassification = null;
        this.WLAddress1 = null;
        this.WLAddress2 = null;
        this.WLCity = null;
        this.WLState = null;
        this.WLCountry = null;
        this.WLZipCode = null;
        this.PlacementPOC = null;
        this.EmployeeID = 0;
        this.IsDeleted = false;
        this.TimeSheet = false;
        this.CompanyID = 0;
        this.CreatedBy = null;
        this.CreatedDate = new Date();
        this.UpdatedBy = null;
        this.UpdatedDate = new Date();
        this.CompanyAssignmentId = null;
        this.PlacementID = 0;
        this.RemoteAssignment = false;
        this.AmendmentRequired = false;
        this.assignDisable = false;
        this.ComapnyEmployeeID = null;
        this.EmployeeFirstName=null;
        this.EmployeeLastName=null;
    }
}


export class DBAssignmentMaster {
    AssignmentID: number;
    CompAssignmentID: number;
    AssignmentName:string;
    Status: number;
    AssignmentType: string;
    AsmtCategory?: number;
    StartDate: Date;
    EndDate?: Date;
    BillingRate: string;
    BillRateType?: number;
    AsmtClassification: string;
    WLAddress1: string;
    WLAddress2: string;
    WLCity: string;
    WLState: string;
    WLCountry: string;
    WLZipCode: string;
    PlacementPOC: string;
    EmployeeID: number;
    IsDeleted: boolean;
    TimeSheet: boolean;
    CompanyID: number;
    CreatedBy: string;
    CreatedDate: Date;
    UpdatedBy: string;
    UpdatedDate?: Date;
    CompanyAssignmentId: string;
    PlacementID:number;
    constructor() {
        this.AssignmentID = 0;
        this.CompAssignmentID = 0;
        this.AssignmentName=null;
        this.Status = 1;
        this.AssignmentType = null;
        this.AsmtCategory = 0;
        this.StartDate = new Date();
        this.EndDate = new Date();
        this.BillingRate = null;
        this.BillRateType = 0;
        this.AsmtClassification = null;
        this.WLAddress1 = null;
        this.WLAddress2 = null;
        this.WLCity = null;
        this.WLState = null;
        this.WLCountry = null;
        this.WLZipCode = null;
        this.PlacementPOC = null;
        this.EmployeeID = 0;
        this.IsDeleted = false;
        this.TimeSheet = false;
        this.CompanyID = 0;
        this.CreatedBy = null;
        this.CreatedDate = new Date();
        this.UpdatedBy = null;
        this.UpdatedDate = new Date();
        this.CompanyAssignmentId = null;
        this.PlacementID=0;
    }
}

export class EmployeeMaster {
    EmployeeID: number;
    CompEmployeeID: number;
    ComapnyEmployeeID:string;
    Status: number;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    Email: string;
    PrimaryPhoneNumber: string;
    SecondaryPhoneNumber: string;
    Address1: string;
    Address2: string;
    City: string;
    State: string;
    Country: string;
    ZipCode: string
    EmployeeType: string;
    EmploymentType: string;
    Classification: string;
    Department: string;
    Designation: string;
    WorkStatus: string;
    WorkStatusExpiry: Date;
    EmpStartDate: Date;
    EmpEndDate: Date;
    HealthInsuranceEnrolled: boolean;
    CandidateID: number;
    Notes: string;
    HRManager: string;
    FinanceManager: string;
    TrainingManager: string;
    ATSManager:string;
    ATSRole:string;
    EMPCentralRole:string;
    CRMRole:string;
    DocVaultRole:string;
    WebsiteUser: string;
    CompanyID: number;
    CreatedBy: string;
    CreatedDate: Date
    UpdatedBy: string;
    UpdatedDate: Date;
    DOB: string;
    Gender: string;
    MaritalStatus: string;
    CreateUserAccount: boolean;
    PlacementID:number;
    HRManager_Name:string;
    AssignmentMasters: AssignmentMaster[];
    EmployeeDocuments:EmployeeDocuments[];
    RemoteAssignment:boolean;
    AmendmentRequired:boolean;
    AssignmentStatus:number;
    LastWorkingDate:string;
    TerminationDate :string;
    TerminationReason :string;
    LaptopReturned :boolean;
    EligibleForRehire :boolean;
    WorkStatusEffective:Date;
    WSExpiryPriority:number;
    StatusName:string;
    FinanceManager_Name:string;
    TrainingManager_Name:string;
    constructor() {
        this.EmployeeID = 0;
        this.CompEmployeeID = 0;
        this.ComapnyEmployeeID=null;
        this.Status = 0;
        this.FirstName = null;
        this.MiddleName = null;
        this.LastName = null;
        this.Email = null;
        this.PrimaryPhoneNumber = null;
        this.SecondaryPhoneNumber = null;
        this.Address1 = null;
        this.Address2 = null;
        this.City = null;
        this.State = null;
        this.Country = null;
        this.ZipCode = null;
        this.EmployeeType = null;
        this.EmploymentType = null;
        this.Classification = null;
        this.Department = null;
        this.Designation = null;
        this.WorkStatus = null;
        this.WorkStatusExpiry = new Date();
        this.EmpStartDate = null;
        this.EmpEndDate = null;
        this.HealthInsuranceEnrolled = false;
        this.CandidateID = 0;
        this.Notes = null;
        this.HRManager = null;
        this.FinanceManager = null;
        this.TrainingManager = null;
        this.ATSManager=null;
        this.ATSRole=null;
        this.EMPCentralRole=null;
        this.CRMRole=null;
        this.DocVaultRole=null;
        this.WebsiteUser = null;
        this.CompanyID = 0;
        this.CreatedBy = null;
        this.CreatedDate = new Date();
        this.UpdatedBy = null;
        this.UpdatedDate = new Date();
        this.DOB = null;
        this.Gender = null;
        this.MaritalStatus = null;
        this.CreateUserAccount= false;
        this.AssignmentMasters= [];
        this.PlacementID=0;
        this.EmployeeDocuments=[];
        this.HRManager_Name=null;
        this.RemoteAssignment=false;
        this.AmendmentRequired=false;
        this.AssignmentStatus=0;
        this.WorkStatusEffective=null;
        this.WSExpiryPriority=0;
        this.StatusName=null;
        this.FinanceManager_Name=null;
        this.TrainingManager_Name=null;
    }
}

export class EmployeeDocuments {
    EmployeeDocumentID: number;
    EmployeeID: number;
    DocumentType: number;
    s3location: string;
    Download_Path_Key: string;
    Download_Path_Type: string;
    DownloadableFileName: string;
    isDeleted: boolean;
    CompanyID: number;
    CreatedBy: string;
    CreatedDate: Date;
    Updatedby: string;
    UpdatedDate: Date;
    DocumentInnerPath:string;
    constructor(){
        this.EmployeeDocumentID=0;
        this.EmployeeID=0;
        this.DocumentType=0;
        this.s3location=null;
        this.Download_Path_Key=null;
        this.Download_Path_Type=null;
        this.DownloadableFileName=null;
        this.isDeleted=false;
        this.CompanyID=0;
        this.CreatedBy=null;
        this.CreatedDate=new Date();
        this.Updatedby=null;
        this.UpdatedDate=new Date();
        this.DocumentInnerPath=null;
    }
}